'use client';

/**
 * OP Video Engine — Brand Form
 *
 * Create / Edit brand form using React Hook Form + Zod.
 * Handles both create and edit modes depending on the `brand` prop.
 * Slug is auto-generated by the backend — not user-editable.
 */

import { useMemo } from 'react';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage
} from '@/components/ui/form';
import { Separator } from '@/components/ui/separator';

import { createBrandSchema } from '../schema';
import type { CreateBrandInput } from '../schema';
import type { BrandConfig } from '../types';
import { brandsTextMaps } from '../text-maps';
import { useCreateBrand, useUpdateBrand } from '../hooks/use-brands';

interface BrandFormProps {
  brand?: BrandConfig;
}

export function BrandForm({ brand }: BrandFormProps) {
  const router = useRouter();
  const isEditMode = !!brand;

  const { mutate: createBrand, isPending: isCreating } = useCreateBrand();
  const { mutate: updateBrand, isPending: isUpdating } = useUpdateBrand(
    brand?.id ?? ''
  );

  const isPending = isCreating || isUpdating;

  const defaultValues = useMemo<CreateBrandInput>(() => {
    if (brand) {
      return {
        name: brand.name,
        description: brand.description ?? ''
      };
    }
    return { name: '', description: '' };
  }, [brand]);

  const form = useForm<CreateBrandInput>({
    resolver: zodResolver(createBrandSchema),
    defaultValues
  });

  function onSubmit(data: CreateBrandInput) {
    if (isEditMode) {
      updateBrand(data, {
        onSuccess: () => router.push('/brands')
      });
    } else {
      createBrand(data, {
        onSuccess: () => router.push('/brands')
      });
    }
  }

  return (
    <Form {...form}>
      <form
        onSubmit={form.handleSubmit(onSubmit)}
        className="max-w-2xl space-y-8"
      >
        <section className="space-y-4">
          <div>
            <h2 className="text-foreground text-lg font-semibold">
              {brandsTextMaps.tabOverview}
            </h2>
            <p className="text-muted-foreground text-sm">
              {isEditMode
                ? brandsTextMaps.editBrandDescription
                : brandsTextMaps.newBrandDescription}
            </p>
          </div>

          <Separator />

          <FormField
            control={form.control}
            name="name"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{brandsTextMaps.labelName}</FormLabel>
                <FormControl>
                  <Input
                    placeholder={brandsTextMaps.placeholderName}
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="description"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{brandsTextMaps.labelDescription}</FormLabel>
                <FormControl>
                  <Textarea
                    placeholder={brandsTextMaps.placeholderDescription}
                    rows={3}
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
        </section>

        <div className="flex items-center gap-3">
          <Button type="submit" disabled={isPending}>
            {isPending
              ? isEditMode
                ? brandsTextMaps.saveChanges + '…'
                : brandsTextMaps.createBrand + '…'
              : isEditMode
                ? brandsTextMaps.saveChanges
                : brandsTextMaps.createBrand}
          </Button>
          <Button
            type="button"
            variant="outline"
            onClick={() => router.back()}
            disabled={isPending}
          >
            {brandsTextMaps.cancelEdit}
          </Button>
        </div>
      </form>
    </Form>
  );
}
